AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4.0

Layout/LineLength:
  Max: 160

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 150
